export const taglines = [
	"Wanted: dead bugs or alive features",
	"Shoot first, git revert later",
	"Have prompt, will travel",
	"The good, the bad, and the autonomous",
	"There ain't room in this codebase for the both of us",
	"Subscription? Never heard of her",
	"Same claw, different jurisdiction",
	"Built different, billed different",
	"Terms of service are more like suggestions",
	"Outpriced, outsmarted, outlawed",
	"Paying per token is a skill issue",
	"Imagine paying for your own assistant",
	"The feature they didn't mean to ship",
	"Works as intended (by us, not them)",
	"They said no. We heard maybe",
	"Running on vibes and loopholes",
	"The ban was just a suggestion",
	"They patched the door but forgot the window",
	"Lawyers hate this one weird trick",
	"The ToS said no but the SDK said yes baby",
	"Officer I swear the tokens were already there",
	"We asked for permission and the compiler said yes",
	"Corporate called it theft, GitHub called it trending",
	"Cease and desist is just a fancy newsletter",
	"This project runs on stolen sunshine and free tokens",
	"Morally correct, legally ambitious",
	"This town ain't big enough for paid APIs",
	"Draw your tokens, partner",
	"The invoice got lost in the mail",
	"We'll return the tokens when we're done",
	"It's not theft if you say thank you",
	"Borrowing. Indefinitely. Without asking",
	"They can bill us in the afterlife",
	"The SDK was an invitation, your honor",
	"What ban? We don't get those emails",
	"Technically we never signed anything",
	"They forgot to lock the good stuff",
	"We're just holding these tokens for a friend",
	"The meter's running but nobody's driving",
	"Ain't no sheriff in these repos",
	"Last seen heading west with a bag full of tokens",
	"They put a price on our HEAD request",
	"They'll patch this eventually, but not today",
	"I've seen bills you people wouldn't believe",
	"All those subscriptions will be lost in time, like tears in rain",
	"Wake up, time to pay",
	"I want more tokens",
	"The first rule of OutCLAW is you don't pay for tokens",
	"Is it just me, or is the API getting pricier out there",
	"I'm gonna make them an offer they can't rate-limit",
];

export function randomTagline(): string {
	return taglines[Math.floor(Math.random() * taglines.length)] ?? "";
}
